<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTG3HngL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTG3HngL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTG3HngL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTG3HngL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTG3HngL\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'TG3HngL',
    'container.build_id' => '88ae523d',
    'container.build_time' => 1558782318,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTG3HngL');
