<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.mcJyH0X' shared service.

return $this->privates['.service_locator.mcJyH0X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'userDTO' => array('privates', 'App\\DTO\\User\\UserDTO', 'getUserDTOService.php', true),
));
