<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Rest\UserController' shared autowired service.

return $this->services['App\Controller\Rest\UserController'] = new \App\Controller\Rest\UserController(new \App\Services\UserService(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')), ($this->privates['App\Repository\UserRepository'] ?? $this->load('getUserRepositoryService.php')), new \App\DTO\User\UserAssembler()), ($this->privates['security.encoder_factory.generic'] ?? $this->load('getSecurity_EncoderFactory_GenericService.php')));
